spring.application.name=SpringGooglelogintest
server.port=8081
spring.security.oauth2.client.registration.google.client-id=176148521531-n9ur9g4fkobre642gvhknsfusu65hqrl.apps.googleusercontent.com
spring.security.oauth2.client.registration.github.client-id=Ov23li3nN9Ksmcs5HuN4
spring.security.oauth2.client.registration.github.client-secret=05689b6c356da639633498102801ea6fbfd6ef93